### ISSUE TITLE
Error in VQA 3Model

### ISSUE THREAD

**Issue by swetha2410** [arya46/VQA_HieCoAtt#1]
Error in build model
The input given to the lstm layer is said to be have an input shape of 2 when instead 3 is actually needed.

**Comment by arya46** [comment]
@swetha2410 What is your tf version? Try to use tf version 2.1. 
I too faced some similar issues when I tried to use tf 2.2. 

Input to LSTM follows the following data flow:

- ques_input [b, max_seq_len] ---> Embedding ----> ques_feat_w [b, max_seq_len, dim_d]

- ques_feat_w [b, max_seq_len, dim_d] ---> PhraseLevelFeatures ---> ques_feat_p [b, max_seq_len, dim_d]
- ques_feat_p [b, max_seq_len, dim_d] ---> LSTM --->  ques_feat_s [b, max_seq_len, dim_d]

As you can clearly see, the input to LSTM is indeed 3-dimensional.

If you still face the issue, let me know how to reproduce the error.

**Comment by swetha2410** [comment]
I am using the tensorflow version used in google colab.

**Comment by swetha2410** [comment]
Could you also tell me how to go about the demo of the model once it has been trained. How can I can input an image and question of my choice and get the model to predict it?

**Comment by arya46** [comment]
@swetha2410 How can I reproduce the error? Otherwise, if I run the same notebook in google colab, there's no issue on my side.
One thing you can do is to try to remove the layers after the `PhraseLevelFeatures` and build it. So you can verify that it returns the desired output of shape `[batch_size, max_seq_len, dim_d]`.
You can use `model.summary()` to print it.

The demo is a flask app. After training the model, you save the model to your disk. 
We extract the VGG19 features from the uploaded image. And tokenize the question data.

These new features are fed into the saved model to predict the answer. It's not that hard to build the demo app. There are a plethora of articles on how to deploy your model.

**Comment by swetha2410** [comment]
@arya46 Thanks! I got the build model working. I installed tensorflow version 2.1 using pip. The default version in colab is 2.2.  How do I create this flask app? Is the code available for that? I haven't used flask before.

**Comment by arya46** [comment]
@swetha2410 yes. the default tf version is 2.2. Glad it worked out for you.

I will upload the project in GitHub by the end of the day. You can fork it from there.

**Comment by swetha2410** [comment]
ThankYou for the timely help.

**Comment by swetha2410** [comment]
I tried the demo like you said. But I keep getting a the same set of answers. Could you share the demo code. I feel like my I got the feature extraction wrong.
Thanks in advance

**Comment by arya46** [comment]
@swetha2410 https://github.com/arya46/VQA_HieCoAtt_App this is the app I used to make the demo video. 

The dataset is highly unbalanced. That is the reason some answers have higher chances to be generated. Look at the `VQA 2 EDA.ipynb` to know more about the dataset.

**Comment by swetha2410** [comment]
Thnks! I had implemented it exactly in this manner. But the answers were mostly yes and no and a long list is given out as the answer. Is there anyway I can improve this? Would increasing the epochs help?

**Comment by arya46** [comment]
@swetha2410 show me the log or screenshot. I cannot understand your issue with mere words.
